export const server = (ctx, x = 0, y = 0) => {
  ctx.save();
  ctx.translate(x, y);
  ctx.miterLimit = 4;
  ctx.fillStyle = "rgba(0,0,0,0)";
  ctx.strokeStyle = "#75FF21";
  ctx.lineWidth = 2;
  ctx.lineJoin = "round";
  ctx.beginPath();
  ctx.moveTo(1, 15);
  ctx.lineTo(28, 15);
  ctx.lineTo(28, 70);
  ctx.lineTo(1, 70);
  ctx.lineTo(1, 15);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();
  ctx.beginPath();
  ctx.moveTo(25, 1);
  ctx.lineTo(52, 1);
  ctx.lineTo(28, 15);
  ctx.lineTo(1, 15);
  ctx.lineTo(25, 1);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();
  ctx.beginPath();
  ctx.moveTo(28, 15);
  ctx.lineTo(53, 1);
  ctx.lineTo(53, 55);
  ctx.lineTo(28, 70);
  ctx.lineTo(28, 15);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();
  ctx.restore();
};
